### ISSUE TITLE
Temping vids causes Naoko to restart

### ISSUE THREAD

**Issue by nuclearace** [awused/cyNaoko#2]
I'm not sure if it's because I'm connected to the server twice from the same computer, once with Naoko, and also logged in, but adding a temp video/temping a video causes her to restart. 

Here is the stack trace:

websocket.pkt  :DEBUG    - Received frame: '5:::{"name":"setTemp","args":[{"uid":15,"temp":true}]}'
Exception in thread Thread-3:
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 552, in __bootstrap_inner
    self.run()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 505, in run
    self.__target(_self.__args, *_self.__kwargs)
  File "/Users/eriklittle/Documents/cyNaoko/naoko/naoko.py", line 386, in _stloop
    self.st_action_queue.popleft()()
  File "/Users/eriklittle/Documents/cyNaoko/naoko/naoko.py", line 44, in action
    fn(_args, *_kwargs)
  File "/Users/eriklittle/Documents/cyNaoko/naoko/naoko.py", line 1015, in setTemp
    self.vidlist[data["idx"]] = self.vidlist[data["idx"]]._replace(temp=data["temp"])
KeyError: 'idx'

**Comment by awused** [comment]
Fixed this. I actually expected, and still expect, more crashes like this related to the Cytube changes.
