### ISSUE TITLE
Clearing a playlist and then adding another one crashes naoko

### ISSUE THREAD

**Issue by nuclearace** [awused/cyNaoko#3]
Clearing a playlist then adding a user playlist seems to cause an infinite crash loop.

Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 552, in __bootstrap_inner
    self.run()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 505, in run
    self.__target(_self.__args, *_self.__kwargs)
  File "/Users/eriklittle/Documents/cyNaoko/naoko/naoko.py", line 386, in _stloop
    self.st_action_queue.popleft()()
  File "/Users/eriklittle/Documents/cyNaoko/naoko/naoko.py", line 44, in action
    fn(_args, *_kwargs)
  File "/Users/eriklittle/Documents/cyNaoko/naoko/naoko.py", line 1043, in playlist
    self._addVideo(v, i, False)
  File "/Users/eriklittle/Documents/cyNaoko/naoko/naoko.py", line 2592, in _addVideo
    assert set(v.keys()) >= set(CytubeVideo._fields) - set(["vidinfo"]), "Video information has changed formats. Unable to continue. Tell Desuwa."
AssertionError: Video information has changed formats. Unable to continue. Tell Desuwa.

**Comment by nuclearace** [comment]
Here is the full run http://pastebin.com/vj4PZWYJ
